# Generated by Django 5.1.7 on 2026-06-28 00:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Syntaxe conseillée : [Quoi] [Seuil] [Où] [Avant quand] ?', max_length=255, verbose_name='Question')),
                ('description', models.TextField(verbose_name='Description / règlement')),
                ('category', models.CharField(choices=[('WEATHER', 'Météo'), ('SOCIAL', 'Réseaux sociaux'), ('TRENDING', 'Tendances')], default='WEATHER', max_length=20, verbose_name='Catégorie')),
                ('source_url', models.URLField(help_text='Source publique de vérification (ex: météo, page Facebook).', verbose_name='Lien source officiel')),
                ('source_rules', models.TextField(help_text='Conduite à adopter si la source est indisponible, litige, etc.', verbose_name='Règles de résolution / litige')),
                ('bet_close_at', models.DateTimeField(help_text='Date/heure limite pour miser (heure de Madagascar).', verbose_name='Clôture des paris')),
                ('resolve_at', models.DateTimeField(help_text='Date/heure à laquelle le résultat peut être vérifié.', verbose_name='Date de vérification')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('OPEN', 'Ouvert'), ('LOCKED', 'Clôturé (en attente vérification)'), ('RESOLVING', 'Résolution en cours'), ('RESOLVED', 'Résolu'), ('CANCELLED', 'Annulé (remboursé)')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('outcome', models.CharField(blank=True, choices=[('YES', 'OUI'), ('NO', 'NON')], max_length=10, verbose_name='Résultat officiel')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('pool_yes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('pool_no', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('image_url', models.URLField(blank=True, verbose_name='Image (optionnel)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_markets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marché',
                'verbose_name_plural': 'Marchés',
                'ordering': ('-is_featured', '-bet_close_at'),
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('YES', 'OUI'), ('NO', 'NON')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Mise')),
                ('payout', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Gain redistribué')),
                ('proba_at_place', models.DecimalField(decimal_places=4, default=Decimal('0.5'), max_digits=6)),
                ('status', models.CharField(choices=[('PLACED', 'Placée'), ('WON', 'Gagnée'), ('LOST', 'Perdue'), ('REFUNDED', 'Remboursée')], default='PLACED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='ledger.ledgerentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='markets.market')),
            ],
            options={
                'verbose_name': 'Pari',
                'verbose_name_plural': 'Paris',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['status', 'category'], name='markets_mar_status_9db0cb_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['-bet_close_at'], name='markets_mar_bet_clo_d9dd10_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['market', 'outcome'], name='markets_bet_market__49f98c_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', '-created_at'], name='markets_bet_user_id_b7c908_idx'),
        ),
    ]
