# Generated by Django 5.1.7 on 2026-06-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='category',
            field=models.CharField(choices=[('WEATHER', 'Météo'), ('SOCIAL', 'Réseaux sociaux'), ('TRENDING', 'Tendances'), ('SPORTS', 'Sport')], default='WEATHER', max_length=20, verbose_name='Catégorie'),
        ),
    ]
