# Generated by Django 5.1.7 on 2026-06-29 19:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_market_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPool',
            fields=[
                ('market', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='pool', serialize=False, to='markets.market')),
                ('escrow_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='MGA bloqués = paires en circulation × 1,00.', max_digits=16, verbose_name='Solde séquestré')),
                ('pairs_created', models.BigIntegerField(default=0)),
                ('pairs_destroyed', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pool de marché',
                'verbose_name_plural': 'Pools de marché',
            },
        ),
        migrations.RemoveField(
            model_name='market',
            name='pool_no',
        ),
        migrations.RemoveField(
            model_name='market',
            name='pool_yes',
        ),
        migrations.AlterField(
            model_name='market',
            name='bet_close_at',
            field=models.DateTimeField(help_text='Date/heure limite pour miser (heure de Madagascar).', verbose_name='Clôture des échanges'),
        ),
        migrations.AlterField(
            model_name='market',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('OPEN', 'Ouvert'), ('LOCKED', 'Clôturé (en attente vérification)'), ('RESOLVING', 'Résolution en cours'), ('RESOLVED', 'Résolu'), ('CANCELLED', 'Annulé (remboursé)'), ('FROZEN', "Gelé (anomalie d'invariance)")], default='DRAFT', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Achat'), ('SELL', 'Vente')], max_length=5)),
                ('order_type', models.CharField(choices=[('LIMIT', 'À cours limité'), ('MARKET', 'Au marché')], max_length=6)),
                ('outcome', models.CharField(choices=[('YES', 'OUI'), ('NO', 'NON')], max_length=3)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Requis pour LIMIT (0,01 à 0,99). Vide pour MARKET.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('0.99'))], verbose_name='Prix limite')),
                ('quantity', models.BigIntegerField(verbose_name='Quantité demandée')),
                ('filled_quantity', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('PARTIAL', 'Partiellement exécuté'), ('FILLED', 'Exécuté'), ('CANCELLED', 'Annulé'), ('EXPIRED', 'Expiré')], default='OPEN', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, help_text="Optionnel : l'ordre expire tout seul après cette date.", null=True, verbose_name='Expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='markets.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordre',
                'verbose_name_plural': 'Ordres',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('YES', 'OUI'), ('NO', 'NON')], max_length=3)),
                ('quantity', models.BigIntegerField(default=0)),
                ('locked_quantity', models.BigIntegerField(default=0)),
                ('avg_buy_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='markets.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('YES', 'OUI'), ('NO', 'NON')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_trades', to='markets.order')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='markets.market')),
                ('sell_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_trades', to='markets.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.DeleteModel(
            name='Bet',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['market', 'outcome', 'side', 'status', 'price'], name='markets_ord_market__4a76a0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='markets_ord_user_id_da24c8_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['market', 'outcome'], name='markets_pos_market__cf3c96_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['user', 'market'], name='markets_pos_user_id_2e5124_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('user', 'market', 'outcome')},
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['market', '-created_at'], name='markets_tra_market__db249a_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['market', 'outcome', '-created_at'], name='markets_tra_market__b91773_idx'),
        ),
    ]
