# Generated by Django 5.1.7 on 2026-06-29 22:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_marketpool_remove_market_pool_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Requis pour LIMIT (1 à 4999 Ar). Vide pour MARKET.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('4999'))], verbose_name='Prix limite'),
        ),
        migrations.AlterField(
            model_name='position',
            name='avg_buy_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
