# Generated by Django 5.1.7 on 2026-06-28 00:08

import django.core.validators
import django.db.models.deletion
import payments.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=payments.models._dep_code, help_text='Code à inclure dans le motif du transfert opérateur.', max_length=20, unique=True, verbose_name='Code de référence')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Montant')),
                ('operator', models.CharField(choices=[('MVOLA', 'MVola'), ('ORANGE', 'Orange Money'), ('AIRTEL', 'Airtel Money')], max_length=10)),
                ('sender_phone', models.CharField(max_length=20, verbose_name='N° expéditeur')),
                ('operator_ref', models.CharField(blank=True, help_text="Identifiant de transaction communiqué par l'opérateur.", max_length=40, verbose_name='Référence SMS opérateur')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de validation'), ('APPROVED', 'Approuvée (créditée)'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, verbose_name='Note admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='ledger.ledgerentry')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deposits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de dépôt',
                'verbose_name_plural': 'Demandes de dépôt',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='payments_de_status_76d43b_idx'), models.Index(fields=['user', '-created_at'], name='payments_de_user_id_cabf81_idx')],
            },
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=payments.models._wdr_code, max_length=20, unique=True, verbose_name='Code de référence')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Montant')),
                ('operator', models.CharField(choices=[('MVOLA', 'MVola'), ('ORANGE', 'Orange Money'), ('AIRTEL', 'Airtel Money')], max_length=10)),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='N° réception')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de transfert'), ('PAID', 'Payée (transfert effectué)'), ('REJECTED', 'Rejetée (montant débloqué)')], default='PENDING', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('operator_ref', models.CharField(blank=True, max_length=40, verbose_name='Référence transfert admin')),
                ('admin_note', models.TextField(blank=True, verbose_name='Note admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='ledger.ledgerentry')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de retrait',
                'verbose_name_plural': 'Demandes de retrait',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='payments_wi_status_ae1176_idx'), models.Index(fields=['user', '-created_at'], name='payments_wi_user_id_f0c00a_idx')],
            },
        ),
    ]
