# Generated by Django 5.1.7 on 2026-06-28 00:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Solde')),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Solde bloqué')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAW', 'Retrait'), ('BET_PLACE', 'Mise de pari'), ('BET_WIN', 'Gain de pari'), ('BET_REFUND', 'Remboursement de pari'), ('ADJUSTMENT', 'Ajustement manuel')], max_length=20, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positif = crédit, négatif = débit.', max_digits=14, verbose_name='Montant signé')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Solde après écriture')),
                ('related_type', models.CharField(blank=True, max_length=30, verbose_name='Type objet lié')),
                ('related_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID objet lié')),
                ('reference', models.CharField(blank=True, help_text='Ex: #DEP-1024, code de référence Mobile Money.', max_length=60, verbose_name='Référence')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.wallet')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='ledger_ledg_wallet__45faba_idx'), models.Index(fields=['type'], name='ledger_ledg_type_7c2656_idx'), models.Index(fields=['reference'], name='ledger_ledg_referen_2059e3_idx')],
            },
        ),
    ]
