# Generated by Django 5.1.7 on 2026-06-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAW', 'Retrait'), ('MINT', 'Émission de paires (débit → séquestre)'), ('MERGE', 'Fusion de paires (crédit ← séquestre)'), ('TRADE_BUY', 'Achat au carnet'), ('TRADE_SELL', 'Vente au carnet'), ('SETTLE_WIN', 'Gain de résolution (1,00 MGA / part)'), ('ORDER_REFUND', "Remboursement d'ordre annulé/expiré"), ('BET_PLACE', '(Obsolète) Mise de pari'), ('BET_WIN', '(Obsolète) Gain de pari'), ('BET_REFUND', '(Obsolète) Remboursement de pari'), ('ADJUSTMENT', 'Ajustement manuel')], max_length=20, verbose_name='Type'),
        ),
    ]
