-- ===========================================================================
--  Nexus v2 — Schéma initial (fidèle au backend Django v1)
--
--  Reproduit les 11 tables du backend Django avec :
--    - contraintes CHECK de non-négativité (gardes B1/B2/B3) ;
--    - index de performance (matching CLOB, requêtes fréquentes) ;
--    - types NUMERIC(14,2) partout pour l'argent (jamais de float).
--
--  Les utilisateurs (auth.users) sont gérés nativement par Supabase Auth.
-- ===========================================================================

-- --------------------------------------------------------------------------
--  Profils utilisateurs (extension de auth.users)
--  Remplace le modèle User custom Django (auth par téléphone Mobile Money).
-- --------------------------------------------------------------------------
create table if not exists public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  phone         varchar(20) unique not null,  -- numéro Mobile Money normalisé (0XXXXXXXXX)
  display_name  varchar(80) default '',
  username      varchar(150),
  is_staff      boolean not null default false,   -- accès dashboard admin
  is_superuser  boolean not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

comment on table public.profiles is 'Profil utilisateur Nexus (extension de auth.users Supabase).';

-- --------------------------------------------------------------------------
--  Wallets — 1 par utilisateur, 1 point = 1 MGA (Ariary).
--  Contraintes CHECK de non-négativité (garde B3 — barrière de dernier recours).
-- --------------------------------------------------------------------------
create table if not exists public.wallets (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null references auth.users(id) on delete restrict,
  balance         numeric(14,2) not null default 0,
  locked_balance  numeric(14,2) not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint wallets_user_id_key unique (user_id),
  -- Gardes B3 : un solde ne peut JAMAIS devenir négatif, même via un bug applicatif.
  constraint wallet_balance_nonneg       check (balance >= 0),
  constraint wallet_locked_balance_nonneg check (locked_balance >= 0)
);

comment on table public.wallets is 'Portefeuille utilisateur. Solde en points (= MGA). locked_balance = fonds séquestrés (ordres/retraits en attente).';

-- --------------------------------------------------------------------------
--  LedgerEntry — écriture comptable IMMUABLE (double-entry).
--  Un montant POSITIF crédite, NÉGATIF débite. L'immuabilité est imposée par
--  un trigger (voir 0002_triggers.sql) — toute modification/suppression lève
--  une erreur, reproduisant save()/delete() bloquants du modèle Django.
-- --------------------------------------------------------------------------
create table if not exists public.ledger_entries (
  id             bigint generated by default as identity primary key,
  wallet_id      bigint not null references public.wallets(id) on delete restrict,
  type           varchar(20) not null,
  amount         numeric(14,2) not null,   -- signé : +crédit / -débit
  balance_after  numeric(14,2) not null,
  related_type   varchar(30) default '',
  related_id     bigint,
  reference      varchar(60) default '',
  note           varchar(255) default '',
  created_by     uuid references auth.users(id) on delete set null,
  created_at     timestamptz not null default now()
);

comment on table public.ledger_entries is 'Écriture comptable immuable. Point d''entrée unique pour tout mouvement de solde.';

create index if not exists ledger_entries_wallet_created_idx
  on public.ledger_entries (wallet_id, created_at desc);
create index if not exists ledger_entries_type_idx
  on public.ledger_entries (type);
create index if not exists ledger_entries_reference_idx
  on public.ledger_entries (reference);

-- --------------------------------------------------------------------------
--  Markets — marché prédictif binaire (OUI/NON), moteur collatéralisé.
-- --------------------------------------------------------------------------
create type public.market_category as enum ('WEATHER', 'SOCIAL', 'TRENDING', 'SPORTS');
create type public.market_outcome as enum ('YES', 'NO');
create type public.market_status as enum
  ('DRAFT', 'OPEN', 'LOCKED', 'RESOLVING', 'RESOLVED', 'CANCELLED', 'FROZEN');

create table if not exists public.markets (
  id            bigint generated by default as identity primary key,
  question      varchar(255) not null,
  description   text not null default '',
  category      public.market_category not null default 'WEATHER',
  source_url    text not null default '',
  source_rules  text not null default '',
  bet_close_at  timestamptz not null,
  resolve_at    timestamptz not null,
  status        public.market_status not null default 'DRAFT',
  outcome       public.market_outcome,                -- NULL tant que non résolu
  resolved_by   uuid references auth.users(id) on delete set null,
  resolved_at   timestamptz,
  image_url     text default '',
  is_featured   boolean not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists markets_status_category_idx on public.markets (status, category);
create index if not exists markets_bet_close_idx        on public.markets (bet_close_at desc);

-- --------------------------------------------------------------------------
--  MarketPool — coffre-fort d'un marché (escrow collatéralisé).
--  INVARIANT : escrow_balance == (pairs_created - pairs_destroyed) × SHARE_VALUE.
-- --------------------------------------------------------------------------
create table if not exists public.market_pools (
  market_id        bigint primary key references public.markets(id) on delete restrict,
  escrow_balance   numeric(16,2) not null default 0,
  pairs_created    bigint not null default 0,
  pairs_destroyed  bigint not null default 0,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  -- Garde B3 : l'escrow ne peut jamais être négatif.
  constraint marketpool_escrow_nonneg check (escrow_balance >= 0)
);

-- --------------------------------------------------------------------------
--  Positions — parts (YES/NO) détenues par un utilisateur sur un marché.
-- --------------------------------------------------------------------------
create table if not exists public.positions (
  id               bigint generated by default as identity primary key,
  user_id          uuid not null references auth.users(id) on delete restrict,
  market_id        bigint not null references public.markets(id) on delete restrict,
  outcome          public.market_outcome not null,
  quantity         bigint not null default 0,
  locked_quantity  bigint not null default 0,
  avg_buy_price    numeric(7,2) not null default 0,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint positions_user_market_outcome_key unique (user_id, market_id, outcome),
  -- Gardes B3 : quantités non-négatives, on ne bloque jamais plus que détenu.
  constraint position_quantity_nonneg   check (quantity >= 0),
  constraint position_locked_nonneg     check (locked_quantity >= 0),
  constraint position_locked_lte_qty    check (locked_quantity <= quantity)
);

create index if not exists positions_market_outcome_idx on public.positions (market_id, outcome);
create index if not exists positions_user_market_idx    on public.positions (user_id, market_id);

-- --------------------------------------------------------------------------
--  Orders — carnet d'ordres (CLOB). LIMIT = prix fixé, MARKET = au meilleur prix.
-- --------------------------------------------------------------------------
create type public.order_side       as enum ('BUY', 'SELL');
create type public.order_type       as enum ('LIMIT', 'MARKET');
create type public.order_status     as enum ('OPEN', 'PARTIAL', 'FILLED', 'CANCELLED', 'EXPIRED');

create table if not exists public.orders (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null references auth.users(id) on delete restrict,
  market_id       bigint not null references public.markets(id) on delete restrict,
  side            public.order_side not null,
  order_type      public.order_type not null,
  outcome         public.market_outcome not null,
  price           numeric(7,2),              -- NULL pour MARKET ; sinon [1, 4999]
  quantity        bigint not null,
  filled_quantity bigint not null default 0,
  status          public.order_status not null default 'OPEN',
  expires_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  -- Gardes B3 : quantité demandée > 0, remplie dans [0, demandée].
  constraint order_quantity_positive   check (quantity > 0),
  constraint order_filled_nonneg       check (filled_quantity >= 0),
  constraint order_filled_lte_quantity check (filled_quantity <= quantity),
  -- Le prix, s'il est défini, doit respecter les bornes légales.
  constraint order_price_bounds check (price is null or (price >= 1 and price <= 4999))
);

-- Index du matching : recherche rapide du meilleur ordre opposé.
create index if not exists orders_matching_idx
  on public.orders (market_id, outcome, side, status, price);
create index if not exists orders_user_created_idx
  on public.orders (user_id, created_at desc);

-- --------------------------------------------------------------------------
--  Trades — transaction exécutée (appariement achat/vente).
-- --------------------------------------------------------------------------
create table if not exists public.trades (
  id           bigint generated by default as identity primary key,
  market_id    bigint not null references public.markets(id) on delete restrict,
  outcome      public.market_outcome not null,
  buyer_id     uuid not null references auth.users(id) on delete restrict,
  seller_id    uuid not null references auth.users(id) on delete restrict,
  buy_order_id  bigint not null references public.orders(id) on delete restrict,
  sell_order_id bigint not null references public.orders(id) on delete restrict,
  price        numeric(7,2) not null,
  quantity     bigint not null,
  created_at   timestamptz not null default now()
);

create index if not exists trades_market_created_idx         on public.trades (market_id, created_at desc);
create index if not exists trades_market_outcome_created_idx on public.trades (market_id, outcome, created_at desc);

-- --------------------------------------------------------------------------
--  Paiements Mobile Money (manuels, validés par admin)
-- --------------------------------------------------------------------------
create type public.payment_operator as enum ('MVOLA', 'ORANGE', 'AIRTEL');
create type public.deposit_status   as enum ('PENDING', 'APPROVED', 'REJECTED');
create type public.withdraw_status  as enum ('PENDING', 'PAID', 'REJECTED');

create table if not exists public.deposit_requests (
  id            bigint generated by default as identity primary key,
  code          varchar(20) unique not null,    -- ex: #DEP-7F3A9C2
  user_id       uuid not null references auth.users(id) on delete restrict,
  amount        numeric(14,2) not null,
  operator      public.payment_operator not null,
  sender_phone  varchar(20) not null,
  operator_ref  varchar(40) default '',
  status        public.deposit_status not null default 'PENDING',
  ledger_entry_id bigint references public.ledger_entries(id) on delete restrict,
  processed_by  uuid references auth.users(id) on delete set null,
  processed_at  timestamptz,
  admin_note    text default '',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  -- Garde B3 : montant de dépôt strictement positif.
  constraint deposit_amount_positive check (amount > 0)
);

create index if not exists deposits_status_created_idx on public.deposit_requests (status, created_at desc);
create index if not exists deposits_user_created_idx   on public.deposit_requests (user_id, created_at desc);

create table if not exists public.withdraw_requests (
  id            bigint generated by default as identity primary key,
  code          varchar(20) unique not null,    -- ex: #WDR-7F3A9C2
  user_id       uuid not null references auth.users(id) on delete restrict,
  amount        numeric(14,2) not null,
  operator      public.payment_operator not null,
  recipient_phone varchar(20) not null,
  status        public.withdraw_status not null default 'PENDING',
  ledger_entry_id bigint references public.ledger_entries(id) on delete restrict,
  processed_by  uuid references auth.users(id) on delete set null,
  processed_at  timestamptz,
  operator_ref  varchar(40) default '',
  admin_note    text default '',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  -- Garde B3 : montant de retrait strictement positif.
  constraint withdraw_amount_positive check (amount > 0)
);

create index if not exists withdrawals_status_created_idx on public.withdraw_requests (status, created_at desc);
create index if not exists withdrawals_user_created_idx   on public.withdraw_requests (user_id, created_at desc);

-- ===========================================================================
--  Fonction utilitaire : updated_at automatique (équivalent auto_now Django).
-- ===========================================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
