-- ===========================================================================
--  Nexus v2 — Migration vers le PARI MUTUEL (modèle broker)
--
--  ANCIEN MODÈLE (Polymarket) : carnet d'ordres + mint de paires + escrow
--  collatéralisé. Complexité élevée, cold start (carnet vide), tu dois
--  avancer ton capital pour semer la liquidité.
--
--  NOUVEAU MODÈLE (pari mutuel / PMU) : le joueur mise sur OUI ou NON, son
--  wallet est débité immédiatement. À la résolution, la plateforme prend
--  10% du pot total et distribue les 90% restants aux gagnants au prorata
--  de leur mise. Tu ne bloques JAMAIS ton capital (pur broker).
--
--  Les anciennes tables (orders, trades, positions, market_pools) sont
--  conservées (pour ne pas casser les FK / ledger existant) mais ne sont plus
--  utilisées. Elles seront vidées puis ignorées.
-- ===========================================================================

-- --------------------------------------------------------------------------
-- 1. Colonnes pari mutuel sur les marchés
-- --------------------------------------------------------------------------
alter table public.markets
  add column if not exists pool_yes numeric(16,2) not null default 0,
  add column if not exists pool_no  numeric(16,2) not null default 0;

-- --------------------------------------------------------------------------
-- 2. Table des paris (bets)
-- --------------------------------------------------------------------------
do $$ begin
  create type public.bet_status as enum ('PENDING', 'WON', 'LOST', 'REFUNDED');
exception when duplicate_object then null; end $$;

create table if not exists public.bets (
  id          bigint generated by default as identity primary key,
  market_id   bigint not null references public.markets(id) on delete restrict,
  user_id     uuid not null references auth.users(id) on delete restrict,
  outcome     public.market_outcome not null,
  amount      numeric(14,2) not null,
  status      public.bet_status not null default 'PENDING',
  payout      numeric(14,2) not null default 0,   -- gain net reçu à la résolution (0 si perdu)
  created_at  timestamptz not null default now(),
  resolved_at timestamptz,
  constraint bet_amount_positive check (amount > 0)
);

create index if not exists bets_market_idx     on public.bets (market_id, outcome);
create index if not exists bets_user_created_idx on public.bets (user_id, created_at desc);
create index if not exists bets_status_idx      on public.bets (status);

-- RLS : un user ne voit que ses paris. Admin voit tout.
alter table public.bets enable row level security;
drop policy if exists bets_select_own on public.bets;
create policy bets_select_own on public.bets
  for select using (user_id = auth.uid() or public.is_platform_admin());

drop policy if exists bets_no_direct_write on public.bets;
create policy bets_no_direct_write on public.bets
  for all using (false) with check (false);


-- ===========================================================================
-- 3. place_bet — le joueur place un pari (débit immédiat)
-- ===========================================================================
create or replace function public.place_bet(
  p_user_id   uuid,
  p_market_id bigint,
  p_outcome   public.market_outcome,
  p_amount    numeric
)
returns public.bets
language plpgsql
security definer
set search_path = public
as $$
declare
  v_market   record;
  v_wallet_id bigint;
  v_row      public.bets;
begin
  if p_amount <= 0 then
    perform public.market_error('La mise doit être positive.');
  end if;

  -- Vérifie que le marché est ouvert et pariable.
  select * into v_market from public.markets where id = p_market_id for update;
  if v_market.status <> 'OPEN' or now() >= v_market.bet_close_at then
    perform public.market_error('Ce marché n''accepte plus de paris.');
  end if;

  select id into v_wallet_id from public.wallets where user_id = p_user_id;

  -- Débit immédiat du wallet (échoue si solde insuffisant, garde CHECK).
  begin
    perform public.post_entry(
      p_wallet_id := v_wallet_id,
      p_entry_type := 'BET',
      p_amount := -p_amount,
      p_related_type := 'bet_market', p_related_id := p_market_id,
      p_reference := '#BET-M' || p_market_id,
      p_note := 'Pari ' || p_outcome || ' sur marché #' || p_market_id,
      p_created_by := p_user_id
    );
  exception when check_violation then
    perform public.market_error('Solde disponible insuffisant pour ce pari.');
  end;

  -- Insère le pari.
  insert into public.bets (market_id, user_id, outcome, amount)
  values (p_market_id, p_user_id, p_outcome, p_amount)
  returning * into v_row;

  -- Incrémente le pool du côté parié.
  if p_outcome = 'YES' then
    update public.markets set pool_yes = pool_yes + p_amount where id = p_market_id;
  else
    update public.markets set pool_no = pool_no + p_amount where id = p_market_id;
  end if;

  return v_row;
end;
$$;


-- ===========================================================================
-- 4. resolve_market v3 (pari mutuel) — distribue les gains + commission
--
--  Logique :
--    pot_total  = pool_yes + pool_no
--    commission = commission_rate% × pot_total → wallet plateforme
--    pot_net    = pot_total - commission
--    Chaque gagnant reçoit : (sa_mise / pool_gagnant) × pot_net
--    Les perdants ne reçoivent rien (déjà débités au place_bet).
-- ===========================================================================
create or replace function public.resolve_market(
  p_market_id  bigint,
  p_outcome    public.market_outcome,
  p_admin_id   uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_market        record;
  v_pot_total     numeric;
  v_pool_winner   numeric;
  v_rate          numeric;
  v_platform_uid  uuid;
  v_platform_wid  bigint;
  v_commission    numeric;
  v_pot_net       numeric;
  v_bet           record;
  v_payout        numeric;
  v_wallet_id     bigint;
  v_count         integer := 0;
begin
  select * into v_market from public.markets where id = p_market_id for update;
  if v_market.status not in ('LOCKED', 'RESOLVING', 'OPEN', 'FROZEN') then
    perform public.market_error('Marché non résolvable.');
  end if;

  -- Gèle le marché.
  update public.markets
    set status = 'RESOLVED', outcome = p_outcome,
        resolved_by = p_admin_id, resolved_at = now()
    where id = p_market_id;

  v_pot_total := v_market.pool_yes + v_market.pool_no;

  -- Cas dégénéré : aucun pari sur ce marché → on termine sans distribution.
  if v_pot_total = 0 then
    return;
  end if;

  -- Config commission.
  select commission_rate, platform_user_id into v_rate, v_platform_uid
    from public.platform_config where id = 1;
  if v_rate is null then v_rate := 0; end if;
  if v_platform_uid is not null then
    select id into v_platform_wid from public.wallets where user_id = v_platform_uid;
  end if;

  -- Commission plateforme (10% du pot total par défaut).
  v_commission := round(v_pot_total * v_rate / 100);
  v_pot_net := v_pot_total - v_commission;

  if v_commission > 0 and v_platform_wid is not null then
    perform public.post_entry(
      p_wallet_id := v_platform_wid,
      p_entry_type := 'SETTLE_FEE',
      p_amount := v_commission,
      p_related_type := 'market', p_related_id := p_market_id,
      p_reference := '#FEE-M' || p_market_id,
      p_note := 'Commission ' || v_rate || '% pari mutuel',
      p_created_by := p_admin_id
    );
  end if;

  -- Pool gagnant (pour calculer la part de chaque gagnant).
  v_pool_winner := case when p_outcome = 'YES' then v_market.pool_yes else v_market.pool_no end;

  -- Distribue aux gagnants (au prorata de leur mise dans le pool gagnant).
  if v_pool_winner > 0 then
    for v_bet in
      select * from public.bets
        where market_id = p_market_id and outcome = p_outcome and status = 'PENDING'
        for update
    loop
      v_payout := round((v_bet.amount / v_pool_winner) * v_pot_net, 2);
      select id into v_wallet_id from public.wallets where user_id = v_bet.user_id;

      perform public.post_entry(
        p_wallet_id := v_wallet_id,
        p_entry_type := 'SETTLE_WIN',
        p_amount := v_payout,
        p_related_type := 'bet', p_related_id := v_bet.id,
        p_reference := '#WIN-M' || p_market_id,
        p_note := 'Gain pari — ' || p_outcome || ' gagnant',
        p_created_by := p_admin_id
      );

      update public.bets
        set status = 'WON', payout = v_payout, resolved_at = now()
        where id = v_bet.id;

      v_count := v_count + 1;
    end loop;
  end if;

  -- Marque les perdants.
  update public.bets
    set status = 'LOST', resolved_at = now()
    where market_id = p_market_id and outcome <> p_outcome and status = 'PENDING';
end;
$$;


-- ===========================================================================
-- 5. cancel_market v2 (pari mutuel) — rembourse tous les paris
-- ===========================================================================
create or replace function public.cancel_market(
  p_market_id bigint,
  p_admin_id  uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_market  record;
  v_bet     record;
  v_wallet_id bigint;
begin
  select * into v_market from public.markets where id = p_market_id for update;
  if v_market.status = 'CANCELLED' then return; end if;

  update public.markets
    set status = 'CANCELLED', resolved_by = p_admin_id, resolved_at = now()
    where id = p_market_id;

  -- Rembourse tous les paris PENDING.
  for v_bet in
    select * from public.bets
      where market_id = p_market_id and status = 'PENDING' for update
  loop
    select id into v_wallet_id from public.wallets where user_id = v_bet.user_id;
    perform public.post_entry(
      p_wallet_id := v_wallet_id,
      p_entry_type := 'BET_REFUND',
      p_amount := v_bet.amount,
      p_related_type := 'bet', p_related_id := v_bet.id,
      p_reference := '#RFD-M' || p_market_id,
      p_note := 'Remboursement — marché annulé',
      p_created_by := p_admin_id
    );
    update public.bets
      set status = 'REFUNDED', resolved_at = now()
      where id = v_bet.id;
  end loop;
end;
$$;


-- ===========================================================================
-- 6. Vue v_bets — paris du joueur (avec labels)
-- ===========================================================================
create or replace view public.v_bets as
select
  b.id, b.market_id,
  m.question as market_question, m.status as market_status,
  m.outcome as market_outcome,
  b.user_id, b.outcome,
  case b.outcome when 'YES' then 'OUI' else 'NON' end as outcome_label,
  b.amount::text as amount, b.payout::text as payout,
  b.status, b.created_at, b.resolved_at
from public.bets b
join public.markets m on m.id = b.market_id;


-- ===========================================================================
-- 7. Labels ledger pour les nouveaux types d'écriture
-- ===========================================================================
create or replace function public.ledger_type_label(t varchar)
returns text language sql immutable as $$
  select case t
    when 'DEPOSIT' then 'Dépôt' when 'WITHDRAW' then 'Retrait'
    when 'MINT' then 'Émission de paires' when 'MERGE' then 'Fusion de paires'
    when 'TRADE_BUY' then 'Achat au carnet' when 'TRADE_SELL' then 'Vente au carnet'
    when 'BET' then 'Pari'
    when 'BET_REFUND' then 'Remboursement de pari'
    when 'SETTLE_WIN' then 'Gain de pari' when 'SETTLE_FEE' then 'Commission plateforme'
    when 'ORDER_REFUND' then 'Remboursement d''ordre'
    when 'ADJUSTMENT' then 'Ajustement manuel' else t end;
$$;


-- ===========================================================================
-- 8. REVOKE sur les nouveaux RPC (sécurité)
-- ===========================================================================
revoke execute on function public.place_bet(uuid, bigint, public.market_outcome, numeric) from anon, authenticated;
