-- ===========================================================================
--  Nexus v2 — Système de parrainage + wagering requirement
--
--  Mécanique :
--    1. Chaque joueur reçoit un code de parrainage unique (ex: NEXU4F2K) à
--       l'inscription, via un trigger sur profiles.
--    2. Un nouvel inscrit peut saisir un code (facultatif) → attach_referral
--       crée une ligne PENDING dans referrals.
--    3. Au 1er dépôt APPROVED du filleul → grant_referral_bonus crédite
--       500 Ar au filleul + 500 Ar au parrain (type BONUS), et incrémente
--       bonus_locked de chacun (wagering requirement).
--    4. À chaque pari (place_bet), bonus_locked est décrémenté du montant
--       misé. Tant que bonus_locked > 0, le retrait est bloqué.
--
--  Audit : verify_invariants tient compte de la masse de bonus émise pour
--  préserver l'invariant de conservation monétaire.
-- ===========================================================================

-- --------------------------------------------------------------------------
-- 1. Colonne bonus_locked sur wallets (wagering requirement)
-- --------------------------------------------------------------------------
alter table public.wallets
  add column if not exists bonus_locked numeric(14,2) not null default 0;
alter table public.wallets
  drop constraint if exists wallet_bonus_locked_nonneg;
alter table public.wallets
  add constraint wallet_bonus_locked_nonneg check (bonus_locked >= 0);


-- --------------------------------------------------------------------------
-- 2. Type enum + tables de parrainage
-- --------------------------------------------------------------------------
do $$ begin
  create type public.referral_status as enum ('PENDING', 'REWARDED');
exception when duplicate_object then null; end $$;

-- Code de parrainage : 1 par utilisateur (PK = user_id).
create table if not exists public.referral_codes (
  user_id   uuid primary key references public.profiles(id) on delete cascade,
  code      varchar(12) not null unique,
  created_at timestamptz not null default now()
);

-- Relation parrainage : 1 filleul = 1 parrain max (unique sur referred_id).
create table if not exists public.referrals (
  id             bigint generated by default as identity primary key,
  referrer_id    uuid not null references public.profiles(id) on delete restrict,
  referred_id    uuid not null references public.profiles(id) on delete restrict,
  status         public.referral_status not null default 'PENDING',
  reward_amount  numeric(14,2) not null default 500,
  created_at     timestamptz not null default now(),
  rewarded_at    timestamptz,
  constraint referrals_referred_unique unique (referred_id),
  constraint referrals_no_self check (referrer_id <> referred_id)
);

create index if not exists referrals_referrer_idx on public.referrals (referrer_id, created_at desc);

-- RLS : un user ne voit que SON code et SES filleuls (côté parrain).
alter table public.referral_codes enable row level security;
drop policy if exists referral_codes_own on public.referral_codes;
create policy referral_codes_own on public.referral_codes
  for select using (user_id = auth.uid());

alter table public.referrals enable row level security;
drop policy if exists referrals_own on public.referrals;
create policy referrals_own on public.referrals
  for select using (referrer_id = auth.uid() or referred_id = auth.uid());

-- Pas d'écriture directe : tout passe par les RPC SECURITY DEFINER.
drop policy if exists referral_codes_no_write on public.referral_codes;
create policy referral_codes_no_write on public.referral_codes
  for all using (false) with check (false);
drop policy if exists referrals_no_write on public.referrals;
create policy referrals_no_write on public.referrals
  for all using (false) with check (false);


-- --------------------------------------------------------------------------
-- 3. Trigger : génère un code unique à la création du profil
-- --------------------------------------------------------------------------
create or replace function public.assign_referral_code()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code  varchar(12);
  v_exists boolean;
  i integer := 0;
begin
  loop
    i := i + 1;
    -- Format : NEXU + 4 alphanumériques majuscules (ex: NEXU4F2K).
    v_code := 'NEXU' || upper(substring(encode(gen_random_bytes(3), 'base64')
      from '[A-Za-z0-9]') for 4);
    select exists(select 1 from public.referral_codes where code = v_code) into v_exists;
    exit when not v_exists or i > 50;
  end loop;

  insert into public.referral_codes (user_id, code) values (new.id, v_code)
    on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_profile_created on public.profiles;
create trigger on_profile_created
  after insert on public.profiles
  for each row execute function public.assign_referral_code();


-- --------------------------------------------------------------------------
-- 4. attach_referral — appelée à l'inscription (lié un filleul à un parrain)
-- --------------------------------------------------------------------------
create or replace function public.attach_referral(
  p_referred_id uuid,
  p_code        varchar
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_referrer_id uuid;
  v_existing uuid;
begin
  if p_code is null or btrim(p_code) = '' then return; end if;

  -- Trouve le parrain via son code.
  select user_id into v_referrer_id from public.referral_codes
    where upper(code) = upper(btrim(p_code));
  if not found then
    raise exception 'Code de parrainage invalide.' using errcode = 'raise_exception';
  end if;

  -- Anti auto-parrainage (doublé par le CHECK, mais message clair).
  if v_referrer_id = p_referred_id then
    raise exception 'Vous ne pouvez pas vous parrainer vous-même.' using errcode = 'raise_exception';
  end if;

  -- Un seul parrain par joueur.
  select referrer_id into v_existing from public.referrals where referred_id = p_referred_id;
  if found then
    raise exception 'Ce compte est déjà parrainé.' using errcode = 'raise_exception';
  end if;

  insert into public.referrals (referrer_id, referred_id, status)
  values (v_referrer_id, p_referred_id, 'PENDING');
end;
$$;


-- --------------------------------------------------------------------------
-- 5. grant_referral_bonus — crédite les deux parties (atomique)
--    Appelée par approve_deposit au 1er dépôt du filleul.
-- --------------------------------------------------------------------------
create or replace function public.grant_referral_bonus(
  p_referral_id bigint,
  p_admin_id    uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ref      record;
  v_amount   numeric;
  v_wid      bigint;
begin
  select * into v_ref from public.referrals where id = p_referral_id for update;
  if not found then return; end if;
  if v_ref.status <> 'PENDING' then return; end if;  -- déjà récompensé

  v_amount := v_ref.reward_amount;  -- 500 par défaut

  -- --- Bonus au FILLEUL ---------------------------------------------------
  select id into v_wid from public.wallets where user_id = v_ref.referred_id;
  perform public.post_entry(
    p_wallet_id := v_wid,
    p_entry_type := 'BONUS',
    p_amount := v_amount,
    p_related_type := 'referral', p_related_id := p_referral_id,
    p_reference := '#BNS-FILLEUL-' || p_referral_id,
    p_note := 'Bonus de parrainage reçu',
    p_created_by := p_admin_id
  );
  update public.wallets set bonus_locked = bonus_locked + v_amount where id = v_wid;

  -- --- Bonus au PARRAIN ---------------------------------------------------
  select id into v_wid from public.wallets where user_id = v_ref.referrer_id;
  perform public.post_entry(
    p_wallet_id := v_wid,
    p_entry_type := 'BONUS',
    p_amount := v_amount,
    p_related_type := 'referral', p_related_id := p_referral_id,
    p_reference := '#BNS-PARRAIN-' || p_referral_id,
    p_note := 'Bonus de parrainage — filleul récompensé',
    p_created_by := p_admin_id
  );
  update public.wallets set bonus_locked = bonus_locked + v_amount where id = v_wid;

  -- Marque la relation comme récompensée.
  update public.referrals
    set status = 'REWARDED', rewarded_at = now()
    where id = p_referral_id;
end;
$$;


-- ===========================================================================
-- 6. approve_deposit v2 — déclenche le bonus de parrainage au 1er dépôt
-- ===========================================================================
create or replace function public.approve_deposit(
  p_deposit_id bigint,
  p_admin_id   uuid,
  p_note       text default ''
)
returns public.deposit_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deposit public.deposit_requests;
  v_wallet_id bigint;
  v_entry_id bigint;
  v_referral_id bigint;
begin
  select * into v_deposit from public.deposit_requests where id = p_deposit_id for update;
  if v_deposit.status <> 'PENDING' then
    raise exception 'Cette demande a déjà été traitée.' using errcode = 'raise_exception';
  end if;

  select id into v_wallet_id from public.wallets where user_id = v_deposit.user_id;
  select public.post_entry(
    p_wallet_id := v_wallet_id,
    p_entry_type := 'DEPOSIT',
    p_amount := v_deposit.amount,
    p_related_type := 'deposit',
    p_related_id := p_deposit_id,
    p_reference := v_deposit.code,
    p_note := coalesce(nullif(p_note, ''), 'Dépôt ' || v_deposit.operator || ' ' || v_deposit.sender_phone),
    p_created_by := p_admin_id
  ).entry_id into v_entry_id;

  update public.deposit_requests
    set status = 'APPROVED', processed_by = p_admin_id, processed_at = now(),
        admin_note = p_note, ledger_entry_id = v_entry_id
    where id = p_deposit_id
    returning * into v_deposit;

  -- --- Bonus de parrainage : si ce déposant est un filleul PENDING --------
  -- C'est le 1er dépôt qui déclenche la récompense (anti-abus).
  select id into v_referral_id from public.referrals
    where referred_id = v_deposit.user_id and status = 'PENDING' limit 1;
  if v_referral_id is not null then
    perform public.grant_referral_bonus(v_referral_id, p_admin_id);
  end if;

  return v_deposit;
end;
$$;


-- ===========================================================================
-- 7. place_bet v2 — décrémente bonus_locked (wagering requirement)
-- ===========================================================================
create or replace function public.place_bet(
  p_user_id   uuid,
  p_market_id bigint,
  p_outcome   public.market_outcome,
  p_amount    numeric
)
returns public.bets
language plpgsql
security definer
set search_path = public
as $$
declare
  v_market   record;
  v_wallet_id bigint;
  v_row      public.bets;
begin
  if p_amount <= 0 then
    perform public.market_error('La mise doit être positive.');
  end if;

  select * into v_market from public.markets where id = p_market_id for update;
  if v_market.status <> 'OPEN' or now() >= v_market.bet_close_at then
    perform public.market_error('Ce marché n''accepte plus de paris.');
  end if;

  select id into v_wallet_id from public.wallets where user_id = p_user_id;

  begin
    perform public.post_entry(
      p_wallet_id := v_wallet_id,
      p_entry_type := 'BET',
      p_amount := -p_amount,
      p_related_type := 'bet_market', p_related_id := p_market_id,
      p_reference := '#BET-M' || p_market_id,
      p_note := 'Pari ' || p_outcome || ' sur marché #' || p_market_id,
      p_created_by := p_user_id
    );
  exception when check_violation then
    perform public.market_error('Solde disponible insuffisant pour ce pari.');
  end;

  -- --- Wagering requirement : chaque mise "consomme" le bonus verrouillé ---
  update public.wallets
    set bonus_locked = greatest(0, bonus_locked - p_amount)
    where id = v_wallet_id;

  insert into public.bets (market_id, user_id, outcome, amount)
  values (p_market_id, p_user_id, p_outcome, p_amount)
  returning * into v_row;

  if p_outcome = 'YES' then
    update public.markets set pool_yes = pool_yes + p_amount where id = p_market_id;
  else
    update public.markets set pool_no = pool_no + p_amount where id = p_market_id;
  end if;

  return v_row;
end;
$$;


-- ===========================================================================
-- 8. request_withdraw v2 — bloque le retrait si bonus_locked > 0
-- ===========================================================================
create or replace function public.request_withdraw(
  p_user_id        uuid,
  p_amount         numeric,
  p_operator       public.payment_operator,
  p_recipient_phone varchar
)
returns public.withdraw_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  v_wallet_id   bigint;
  v_bonus_locked numeric;
  v_row         public.withdraw_requests;
begin
  select id, bonus_locked into v_wallet_id, v_bonus_locked
    from public.wallets where user_id = p_user_id;

  -- --- Wagering requirement : bonus non retirable tant qu'il est misé ------
  if v_bonus_locked > 0 then
    raise exception
      'Votre bonus de parrainage (%) doit être entièrement misé avant tout retrait.',
      v_bonus_locked
      using errcode = 'raise_exception';
  end if;

  begin
    perform public.post_entry(
      p_wallet_id := v_wallet_id,
      p_entry_type := 'WITHDRAW',
      p_amount := -p_amount,
      p_lock := true,
      p_related_type := 'withdraw',
      p_reference := '#WDR-LOCK',
      p_note := 'Blocage retrait ' || p_operator || ' vers ' || p_recipient_phone,
      p_created_by := p_user_id
    );
  exception when check_violation then
    raise exception 'Solde disponible insuffisant.' using errcode = 'raise_exception';
  end;

  insert into public.withdraw_requests
    (code, user_id, amount, operator, recipient_phone, status)
  values
    (public.gen_payment_code('WDR'), p_user_id, p_amount, p_operator, p_recipient_phone, 'PENDING')
  returning * into v_row;
  return v_row;
end;
$$;


-- ===========================================================================
-- 9. ledger_type_label v2 — ajoute le label BONUS
-- ===========================================================================
create or replace function public.ledger_type_label(t varchar)
returns text language sql immutable as $$
  select case t
    when 'DEPOSIT' then 'Dépôt' when 'WITHDRAW' then 'Retrait'
    when 'MINT' then 'Émission de paires' when 'MERGE' then 'Fusion de paires'
    when 'TRADE_BUY' then 'Achat au carnet' when 'TRADE_SELL' then 'Vente au carnet'
    when 'BET' then 'Pari'
    when 'BET_REFUND' then 'Remboursement de pari'
    when 'SETTLE_WIN' then 'Gain de pari' when 'SETTLE_FEE' then 'Commission plateforme'
    when 'BONUS' then 'Bonus de parrainage'
    when 'ORDER_REFUND' then 'Remboursement d''ordre'
    when 'ADJUSTMENT' then 'Ajustement manuel' else t end;
$$;


-- ===========================================================================
-- 10. verify_invariants v3 — tient compte de la masse de bonus émise
--     Invariant : Σbalances + Σescrow == Σdépôts − Σretraits + Σbonus
-- ===========================================================================
create or replace function public.verify_invariants()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_report jsonb;
  v_total_balance numeric;
  v_total_escrow numeric;
  v_deposits_in numeric;
  v_withdrawals_out numeric;
  v_total_bonus numeric;
  v_actual numeric;
  v_expected numeric;
  v_global_ok boolean := true;
  v_global jsonb;
begin
  -- Invariant global (conservation de la masse monétaire).
  -- Les bonus de parrainage sont de la monnaie émise par la plateforme :
  -- ils s'ajoutent au côté « attendu » pour préserver l'audit.
  select coalesce(sum(balance), 0) into v_total_balance from public.wallets;
  select coalesce(sum(escrow_balance), 0) into v_total_escrow from public.market_pools;
  select coalesce(sum(amount), 0) into v_deposits_in
    from public.deposit_requests where status = 'APPROVED';
  select coalesce(sum(amount), 0) into v_withdrawals_out
    from public.withdraw_requests where status = 'PAID';
  select coalesce(sum(amount), 0) into v_total_bonus
    from public.ledger_entries where type = 'BONUS';

  v_actual := v_total_balance + v_total_escrow;
  v_expected := v_deposits_in - v_withdrawals_out + v_total_bonus;

  if v_actual <> v_expected then
    v_global_ok := false;
    v_global := jsonb_build_object(
      'actual', v_actual, 'expected', v_expected,
      'balance', v_total_balance, 'escrow', v_total_escrow,
      'deposits_in', v_deposits_in, 'withdrawals_out', v_withdrawals_out,
      'bonus_issued', v_total_bonus
    );
  end if;

  return jsonb_build_object(
    'global_invariant_ok', v_global_ok,
    'global', coalesce(v_global, 'null'::jsonb)
  );
end;
$$;


-- ===========================================================================
-- 11. REVOKE sur les nouveaux RPC (sécurité)
-- ===========================================================================
revoke execute on function public.attach_referral(uuid, varchar) from anon, authenticated;
revoke execute on function public.grant_referral_bonus(bigint, uuid) from anon, authenticated;
